---
title: "2-14: Debugging External Scripts (Unfinished)"
short: "2-14"
# special characters for highlighting code : «»
---

### This lesson is not yet fit for student consumption

Hopefully, it will be in January 2026

## Purpose

-   Use browser() to debug external script (don't forget to remove browser()

-   Alternate ways to debug script

-   Downloading package script and debugging those

## Material

The [script for the lesson is here](../scripts/2-13_Breakpoints_new.R)

A [second script that contains a function to debug](../scripts/debugTest.r)

The [data used for the lesson](../data/Lansing2016Noaa-3.csv) is here

## Adding breakpoints to external scripts

\<talk about how external script should only contain functions – why is an app question\>

\<often need to clear all bp\>

note: bp works under some circumstances in external script

source main, sources external: no

source main, debugSource external: yes

source external, put in breakpoint, run from main: yes

put in breakpoint, source external, run from main: yes

 

In last lesson, we learned how to put an R script in debug mode using the RStudio interface to add a breakpoint in the gutter area of the script. This method works well for debugging your main script (the script you Source). However, you will likely find yourself wanting to add a breakpoint to a external script called by your main script. This could either be a functions script or a script from a package. Adding breakpoints to external scripts called from your main script is not quite as simple. In this lesson we will learn how to add breakpoints to scripts outside of your main script

-   Adding breakpoints (gutter) to external script (probably not a good idea...)

    -   if using source(), bp must be added after

        -   source() removes bp

    -   you must then Run the function

        -   bp will not work on source()

        -   be careful with rm(list=...)

## browser()

As a general rule, it is easiest to use breakpoints in the script you are Sourcing and browser() in scripts that

 

The most universal way to add a breakpoint is to add the command ***browser()*** to the location in your script where you want the breakpoint. ***browser()*** acts just like a breakpoint by pausing your script and putting your script in debug mode. We can take examples from the last lesson and replace the breakpoint with ***browser()***. [Note: browser() is added to your script and needs to be removed after debugging.]{.hl}

### browser() in the main script

In last lesson, the first breakpoint we set was on line 8. Instead of a breakpoint, we can put a browser() command to put the script in debug mode:

``` r
rm(list=ls());  
source("scripts/debugTest.r");

weatherData = read.csv(file = "data/lansing2016Noaa-3.csv");
highTemps = weatherData$maxTemp;
lowTemps = weatherData$minTemp;
«browser()»
diffTemp = highTemps - lowTemps;

weatherData$diffTemp = diffTemp;
```

Note: bp essentially injected browser() into script. Almost... because RStudio cannot see the injected browser() until after commands have been executed

-   do examples from last lesson

-   then put the script in a function and call from a second script \[or, use 1-15 function's script?\]

-   mention that most external scripts contain functions

\<bad regarding browser in main script: does not work in Run\>

### add browser to code

We can add browser() to line 7 of the script from last lesson and click Source. You will see the familiar debug features

 

\<image of browser() with green arrow – controls are the same as bp\>

### add browser to for loop \<need?? – just need to say it can replace bp\>

Instead of putting a NULL command in a for loop so that a breakpoint can be put on the line, we can put browser(). Don't forget to remove or comment out browser() when you are done debugging

\<link back to last lesson's NULL in for loops\>

\<image for loop with two browser() instead of NULL\>

### Don't forget to remove browser()

## Named lists

\<pass in named List to function ... with high, low, and dates\>

\<highest high external script\>

 

 

## browser() in function scripts

 

The main reason to use browser() is that it work in script files outside of script being Sourced. In the script files, we call a second script named \< \>. This script has functions in used by the main script. Adding breakpoints to the functions script will not work if you Source the main script. However, adding browser() will work.

## Downloading package script

-   packages are external scripts

-   unzip to project folder

-   show function folder

### Including downloaded package scripts

-   load with pkgload

-   does not show in Environment

### added browser() to downloaded scripts

-   can now debug

-   note: you can also modify the package function

## Application

Why should external scripts only contain functions?

Create a function that returns a named list with attributes

## Extension: Next in advanced class

-   trace() to inject code

-   functional programming

-   object-oriented programming (S3 vs S7 objects)

-   Environment and variable scope

    -   why if-else works in f() and for loops

-   commands and subcommands in R { }

-   Rcpp

## Extension: Different approaches to breakpoints

### source() outside script first, add breakpoints

-   do not source() or rm(list=lm()) in main script

-   only works when Run

### source() from main script, add breakpoints, run function

-   do not source() or rm(list=lm()) in main script

-   only works when Run

-   does it work if you put the bp on the function??

    -   No, because source()

### add breakpoints, debugSource() from main script, run function

-   do not source() or rm(list=lm()) in main script

-   only works when Run

-   does it work if you put the bp on the function??

    -   no, it gets really weird!

### Debugging 4 scenarios

1\) Within main (sourced) script

-   breakpoint

-   browser

    -   but, browser() needs to be encapsulated between { }

2\) Function outside your main (sourced) script

-   browser() : inconsistent in main script, works in functions

-   source functions script from main, add breakpoint, Run function from main

    -   external breakpoint are broken when file is sourced

3\) External script (not a function script) – No!

-   done rarely and bad practice, and a pain to debug, so probably not going to teach

4\) Function in package

-   download package to computer

-   load with pkgload

-   can use browser() as if this were scenario 2
